--CREATE TABLE IF NOT EXISTS chatroom (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    title VARCHAR(255),
--    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
--);


CREATE TABLE users (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    email VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    phone VARCHAR(255),
    role VARCHAR(20),
    user_type VARCHAR(20)
);



CREATE TABLE email_verification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255),
    email VARCHAR(255),
    expired_at DATETIME,
    verified TINYINT(1) NOT NULL DEFAULT 0
);

CREATE TABLE inquiry_chat (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 owner_id BIGINT DEFAULT NULL,
 user_id BIGINT DEFAULT NULL,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (owner_id)
 REFERENCES users(id),

 FOREIGN KEY (user_id)
 REFERENCES users(id),

  CONSTRAINT uk_inquiry_chat_user_owner
  UNIQUE (user_id,owner_id)
);

CREATE TABLE message (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content VARCHAR(255),
  sender VARCHAR(255),
  user_id BIGINT,
  chatroom_id BIGINT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id)
  REFERENCES users(id),

  FOREIGN KEY (chatroom_id)
  REFERENCES inquiry_chat(id)

);

CREATE TABLE refresh_entity(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 expiration VARCHAR(255) ,
 refresh VARCHAR(255),
 username VARCHAR(255)
);


CREATE TABLE user_chatroom_mapping (

 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 chatroom_id BIGINT,
 user_id BIGINT,

 FOREIGN KEY (chatroom_id)
 REFERENCES inquiry_chat(id),

 FOREIGN KEY (user_id)
 REFERENCES users(id)
);


-- 레스토랑 이미지 및 레스토랑 키워드는 따로 테이블로 분류
CREATE TABLE restaurant (

 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 owner_id BIGINT,
 name VARCHAR(255),
 business_number VARCHAR(12),
 description TEXT,
 category VARCHAR(20),
 phone VARCHAR(255),
 address VARCHAR(255),
 latitude DECIMAL(10,7),
 longitude DECIMAL(10,7),
 open_time TIME,
 close_time TIME,
 has_break_time TINYINT(1) DEFAULT 0,
 break_start_time TIME,
 break_end_time TIME,
 image_key VARCHAR(255),

 FOREIGN KEY (owner_id)
 REFERENCES users(id)
);

CREATE TABLE restaurant_keyword(

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    keyword VARCHAR(255),

    FOREIGN KEY (restaurant_id)
    REFERENCES restaurant(id)
);

CREATE TABLE restaurant_images(

 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 restaurant_id BIGINT NOT NULL,
 image_key VARCHAR(255),

 FOREIGN KEY (restaurant_id)
 REFERENCES restaurant(id)

);

